name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
    paths:
      - '*.sh'
      - '*.json'
      - '.github/workflows/**'
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

env:
  PROJECT_NAME: weup-dns-toolkit

jobs:
  lint:
    name: Lint & Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run ShellCheck on main script
        run: shellcheck -x -s bash dns_toolkit.sh

      - name: Run ShellCheck on install script
        run: shellcheck -x -s bash install.sh

      - name: Validate JSON dataset
        run: |
          echo "Validating dns_dataset.json..."
          jq empty dns_dataset.json
          echo "JSON is valid"

      - name: Check JSON structure
        run: |
          # Verify required fields exist
          jq -e '.version' dns_dataset.json > /dev/null
          jq -e '.dns_providers' dns_dataset.json > /dev/null
          jq -e '.test_domains' dns_dataset.json > /dev/null
          echo "JSON structure is valid"

      - name: Count DNS providers
        run: |
          count=$(jq '[.dns_providers[][] | select(.providers != null) | .providers[]] | length' dns_dataset.json)
          echo "Total DNS providers: $count"
          if [ "$count" -lt 50 ]; then
            echo "Warning: Less than 50 providers in dataset"
          fi

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        ubuntu: ['20.04', '22.04', '24.04']
    container:
      image: ubuntu:${{ matrix.ubuntu }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y jq curl dnsutils gawk coreutils util-linux

      - name: Run test suite
        run: |
          chmod +x tests/test_dns_toolkit.sh
          ./tests/test_dns_toolkit.sh

      - name: Test script execution
        run: |
          chmod +x dns_toolkit.sh
          ./dns_toolkit.sh --version
          ./dns_toolkit.sh --help

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run security checks
        run: |
          # Check for potential command injection patterns
          echo "Checking for command injection vulnerabilities..."
          if grep -rn 'eval\s' dns_toolkit.sh | grep -v '^#'; then
            echo "Warning: eval usage found"
          fi
          
          # Check for unsafe variable usage
          echo "Checking for unsafe variable expansion..."
          if grep -rn '\$\{.*\}' dns_toolkit.sh | grep -v '"' | head -20; then
            echo "Note: Some unquoted variable expansions (review required)"
          fi

      - name: Check for hardcoded credentials
        run: |
          echo "Checking for hardcoded credentials..."
          if grep -rniE '(password|secret|token|api_key)\s*=' . --include='*.sh' --include='*.json' | grep -v '^#'; then
            echo "Warning: Potential hardcoded credentials found"
            exit 1
          fi
          echo "No hardcoded credentials found"

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl dnsutils gawk

      - name: Test DNS resolution functions
        run: |
          chmod +x dns_toolkit.sh
          
          # Source the script to test functions
          source dns_toolkit.sh --help 2>/dev/null || true
          
          # Test basic DNS resolution
          echo "Testing DNS resolution..."
          dig +short google.com @1.1.1.1 || echo "DNS test completed"

      - name: Test dataset loading
        run: |
          echo "Testing dataset parsing..."
          jq -r '.dns_providers.iranian.providers[0].name' dns_dataset.json
          jq -r '.dns_providers.international.providers[0].name' dns_dataset.json
          echo "Dataset parsing successful"

      - name: Verify Iranian DNS entries
        run: |
          echo "Verifying Iranian DNS providers..."
          shecan_ip=$(jq -r '.dns_providers.iranian.providers[] | select(.id == "shecan") | .protocols.dns.ipv4[0]' dns_dataset.json)
          echo "Shecan IP: $shecan_ip"
          if [ "$shecan_ip" != "178.22.122.100" ]; then
            echo "Error: Shecan IP mismatch"
            exit 1
          fi
          echo "Iranian DNS entries verified"

  build:
    name: Build Release Package
    runs-on: ubuntu-latest
    needs: [test, security, integration]
    if: github.event_name == 'release'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create release package
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          PACKAGE_NAME="${PROJECT_NAME}-${VERSION}"
          
          mkdir -p "${PACKAGE_NAME}"
          
          # Copy main files
          cp dns_toolkit.sh "${PACKAGE_NAME}/"
          cp dns_dataset.json "${PACKAGE_NAME}/"
          cp install.sh "${PACKAGE_NAME}/"
          cp config.conf "${PACKAGE_NAME}/"
          cp README.md "${PACKAGE_NAME}/"
          cp CHANGELOG.md "${PACKAGE_NAME}/"
          cp LICENSE "${PACKAGE_NAME}/"
          
          # Copy tests
          mkdir -p "${PACKAGE_NAME}/tests"
          cp -r tests/* "${PACKAGE_NAME}/tests/"
          
          # Create tarball
          tar -czvf "${PACKAGE_NAME}.tar.gz" "${PACKAGE_NAME}"
          
          # Create checksum
          sha256sum "${PACKAGE_NAME}.tar.gz" > "${PACKAGE_NAME}.tar.gz.sha256"

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-package
          path: |
            *.tar.gz
            *.sha256

  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-package

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.tar.gz
            *.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    name: Notify on Failure
    runs-on: ubuntu-latest
    needs: [lint, test, security, integration]
    if: failure()
    steps:
      - name: Create failure notification
        run: |
          echo "CI Pipeline failed!"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Workflow: ${{ github.workflow }}"
